# FILE: app/services/email_service.py
# ==============================================================================
# Handles all email-related tasks for the two-phase workflow.
# The ingestion function polls a single mailbox (which can be shared by
# multiple configurations) and uses a dispatcher model to route requests
# to the correct workflow based on the content of the email.
# ==============================================================================

import imaplib
import email
from email.header import decode_header
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import logging
import re
from datetime import datetime

from app.services import db_service, ad_service
from app.services.ai_service import analyze_email

# Regular expression for matching automated email addresses to ignore them.
AUTO_ADDRESS_PATTERNS = [
    r'no-?reply@', r'notification', r'do-?not-?reply@', r'mailer-daemon', r'postmaster@',
    r'automated', r'helpdesk', r'bounces@', r'^noreply', r'bot@', r'listserv',
    r'system@', r'alerts?@'
]

# --- Utility Functions ---

def is_autogenerated_address(email_address):
    """Checks if an email address matches common patterns for automated senders."""
    if not email_address:
        return True
    return any(re.search(pat, email_address, re.IGNORECASE) for pat in AUTO_ADDRESS_PATTERNS)

def extract_email(from_header):
    """Extracts a clean email address from a 'From' header string."""
    if not from_header:
        return None
    match = re.search(r'<([^>]+)>', from_header)
    if match:
        return match.group(1).strip().lower()
    match = re.search(r'[\w.\-+]+@[\w.\-]+', from_header)
    if match:
        return match.group(0).strip().lower()
    return None

def get_email_body(msg):
    """Extracts the plain text body from an email message object."""
    if msg.is_multipart():
        for part in msg.walk():
            content_type = part.get_content_type()
            content_disp = str(part.get("Content-Disposition") or "")
            if content_type == "text/plain" and "attachment" not in content_disp.lower():
                try:
                    return part.get_payload(decode=True).decode()
                except (UnicodeDecodeError, AttributeError):
                    return part.get_payload(decode=True).decode('latin-1', errors='ignore')
    else:
        try:
            return msg.get_payload(decode=True).decode()
        except (UnicodeDecodeError, AttributeError):
            return msg.get_payload(decode=True).decode('latin-1', errors='ignore')
    return ""

def build_search_query(last_check_timestamp):
    """Builds the IMAP search query based on the last check timestamp."""
    search_date = datetime.fromisoformat(last_check_timestamp).strftime('%d-%b-%Y')
    return f'(SINCE "{search_date}")'

def send_email(recipients, subject, body, config):
    """Sends an email using the merged config which contains all necessary credentials."""
    msg = MIMEMultipart()
    msg['From'] = f"{config['team_alias']} <{config['smtp_user']}>"
    msg['To'] = ", ".join(recipients)
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))
    try:
        with smtplib.SMTP(config['smtp_server'], config['smtp_port']) as server:
            server.starttls()
            server.login(config['smtp_user'], config['smtp_pass'])
            server.send_message(msg)
            logging.info(f"Sent email '{subject}' to {recipients}")
    except Exception as e:
        logging.error(f"Failed to send email '{subject}' to {recipients}: {e}", exc_info=True)

# ==============================================================================
# Phase 1: Ingestion Worker (Read & Record)
# ==============================================================================

def ingest_emails_to_db(mailbox_config, associated_configs, static_config):
    """
    PHASE 1: Polls ONE mailbox and dispatches emails to its associated configurations.
    """
    mailbox_id = mailbox_config['id']
    full_mailbox_config = {**static_config, **mailbox_config}
    last_check_timestamp_key = f"MAILBOX_{mailbox_id}"
    last_check_timestamp = db_service.get_last_check_time(last_check_timestamp_key, full_mailbox_config)
    
    group_config_map = {
        (c.get('required_ad_group') or '').upper(): c
        for c in associated_configs
    }

    try:
        with imaplib.IMAP4_SSL(full_mailbox_config['imap_server']) as mail:
            mail.login(full_mailbox_config['imap_user'], full_mailbox_config['imap_pass'])
            mail.select("INBOX")
            search_query = build_search_query(last_check_timestamp)
            status, message_data = mail.uid('search', None, search_query)
            if status != "OK":
                logging.error(f"[Mailbox ID: {mailbox_id}] IMAP search failed.")
                return

            all_uids = message_data[0].split()
            if all_uids:
                logging.info(f"[Mailbox ID: {mailbox_id}] Found {len(all_uids)} new emails to process.")
            
            for uid in all_uids:
                uid_str = uid.decode()
                if not db_service.claim_uid_for_processing(uid_str):
                    continue

                try:
                    fetch_status, msg_parts = mail.uid('fetch', uid, '(RFC822)')
                    if fetch_status != 'OK' or not msg_parts or not msg_parts[0]:
                        logging.error(f"Failed to fetch email content for UID {uid_str}. Status: {fetch_status}.")
                        continue
                    
                    msg = email.message_from_bytes(msg_parts[0][1])
                    subject, _ = decode_header(msg.get("Subject") or "")[0]
                    if isinstance(subject, bytes): subject = subject.decode('utf-8', 'ignore')
                    
                    sender_email = extract_email(msg.get("From"))
                    if not sender_email or is_autogenerated_address(sender_email):
                        continue

                    body = get_email_body(msg)
                    analysis = analyze_email(subject, body, full_mailbox_config)
                    if not analysis:
                        logging.warning(f"AI analysis for UID {uid_str} failed. Skipping.")
                        continue

                    intent = analysis.get('intent')
                    user_email = analysis.get('user_email')

                    if intent == 'new_request':
                        requested_group = (analysis.get('requested_group') or '').upper()
                        target_config = group_config_map.get(requested_group)
                        if target_config:
                            logging.info(f"Staging new request for user '{user_email}' for config '{target_config['config_id']}'.")
                            db_service.create_onboarding_request_composite(
                                user_email=user_email,
                                group=requested_group,
                                config_id=target_config['config_id']
                            )
                        else:
                            logging.warning(f"Request for group '{requested_group}' received in mailbox {mailbox_id}, but no matching config found.")
                    
                    elif intent == 'approval':
                        if not user_email: continue
                        active_request = db_service.find_active_request_by_user(user_email)
                        if active_request:
                            target_config = next((c for c in associated_configs if c['config_id'] == active_request['config_id']), None)
                            if target_config:
                                full_workflow_config = {**static_config, **mailbox_config, **target_config}
                                handle_approval_email(
                                    from_email=sender_email,
                                    user_email=user_email,
                                    requested_group=active_request['requested_group'],
                                    config=full_workflow_config
                                )
                            else:
                                logging.warning(f"Approval for '{user_email}' found, but their active request (config_id: {active_request['config_id']}) is not associated with this mailbox (ID: {mailbox_id}).")
                        else:
                            logging.warning(f"Approval received for user '{user_email}' but no active request was found.")

                except Exception as e:
                    logging.error(f"[Mailbox ID: {mailbox_id}] Exception processing UID {uid_str}: {e}", exc_info=True)

            db_service.update_last_check_time(last_check_timestamp_key, datetime.now().isoformat())
    except Exception as e:
        logging.error(f"[Mailbox ID: {mailbox_id}] Could not access mailbox: {e}", exc_info=True)

# ==============================================================================
# Phase 2: Action Worker (Wait & Execute)
# ==============================================================================

def process_pending_actions(config):
    """
    PHASE 2: Queries for "matured" requests for a specific config and acts on them.
    """
    config_id = config['config_id']
    try:
        mature_requests = db_service.get_mature_unprocessed_requests(config_id, config)
        if mature_requests:
             logging.info(f"[{config_id}] Found {len(mature_requests)} mature requests to process.")
        
        for request in mature_requests:
            user_email = request['user_to_onboard_email']
            requested_group = request['requested_group']
            logging.info(f"[{config_id}] Evaluating mature request for user '{user_email}'.")

            # ===== FIX STARTS HERE =====
            # Bug Fix: The logic here now mirrors the robust, recursive logic of handle_approval_email
            # to ensure stages are advanced correctly even in proactive approval scenarios.
            
            # Check if any approvers can be found. If not, it's a config error.
            required_approvers = db_service.get_required_approvers_for_stage(request, config)
            if not required_approvers:
                error_msg = f"Could not find any required approvers for stage {request['current_stage']}. Check AD configuration."
                logging.error(f"[{config_id}] {error_msg}")
                db_service.update_request_status_composite(user_email, requested_group, config_id, 'error', error_msg)
                continue 

            # Check if there are still approvers missing for the current stage.
            missing_approvers = db_service.get_missing_approvers_for_stage(request, config)
            
            if not missing_approvers:
                # This stage is pre-approved. We can now use the main approval handler
                # to advance the stage and re-evaluate, ensuring the full workflow runs.
                logging.info(f"[{config_id}] Stage {request['current_stage']} for '{user_email}' is pre-approved. Advancing workflow.")
                # We pass a dummy email for the 'from_email' as it's not needed for this logic path.
                handle_approval_email("system.preapproved@local", user_email, requested_group, config)
            else:
                # Approvals are missing, so we start the standard process by sending an email.
                logging.info(f"[{config_id}] Approvals missing for '{user_email}'. Initiating approval process.")
                send_request_to_next_stage(request, config)
            # ===== FIX ENDS HERE =====

    except Exception as e:
        logging.error(f"[{config_id}] Error processing pending actions: {e}", exc_info=True)

# --- Approval and Reminder Logic ---

def handle_approval_email(from_email, user_email, requested_group, config):
    """
    Handles approval emails for an onboarding request (manager/system owner etc).
    If all approvals are present (even by duplicate/resent email), onboarding will progress.
    """
    config_id = config['config_id']
    request = db_service.get_active_request(user_email, requested_group, config_id)
    if not request:
        logging.warning(f"[{config_id}] Approval received but no active request found for {user_email} / {requested_group}.")
        return

    if request['status'] == 'completed':
        logging.info(f"[{config_id}] Approval received for user {user_email} but onboarding already completed. Ignoring.")
        return

    approver_email = extract_email(from_email).lower()
    effective_approvers = db_service.get_effective_approvers_for_stage(request, config)

    if approver_email not in effective_approvers:
        logging.warning(f"[{config_id}] Unauthorized approval attempt by {approver_email} for user {user_email}.")
        return

    approval_added = db_service.add_stage_approval(request, approver_email, config)
    if not approval_added:
        logging.info(f"[{config_id}] Approval by {approver_email} was already recorded or failed for user {user_email}.")
        # PATCH: If already recorded, still check if ALL required approvals are present!
        # >>> BEGIN PATCH <<<
        missing = db_service.get_missing_approvers_for_stage(request, config)
        if not missing:
            if request['current_stage'] >= 2:
                db_service.onboard_user_to_target_db(user_email, config)
                db_service.update_request_status_composite(user_email, requested_group, config_id, 'completed', 'Access granted after approval (idempotent check).')
                send_confirmation_email(user_email, config)
                logging.info(f"[{config_id}] (Idempotent/duplicate) Onboarded user {user_email} for group {requested_group} after approval.")
            else:
                advanced_request = db_service.advance_to_next_stage_composite(user_email, requested_group, config_id)
                if advanced_request:
                    send_request_to_next_stage(advanced_request, config)
                    logging.info(f"[{config_id}] (Idempotent/duplicate) Advanced request for {user_email} to next stage after approval.")
                else:
                    logging.error(f"[{config_id}] Failed to advance request stage for {user_email} / {requested_group}.")
        else:
            logging.info(f"[{config_id}] Approval not advanced; waiting for other approvals or actions (idempotent check).")
        # <<< END PATCH >>>
        return

    # Now a new approval was added, check if all approvals are done
    missing = db_service.get_missing_approvers_for_stage(request, config)
    if not missing:
        # All approvals complete, onboard or advance
        if request['current_stage'] >= 2:
            db_service.onboard_user_to_target_db(user_email, config)
            db_service.update_request_status_composite(user_email, requested_group, config_id, 'completed', 'Access granted after approval.')
            send_confirmation_email(user_email, config)
            logging.info(f"[{config_id}] Onboarded user {user_email} for group {requested_group} after approval.")
        else:
            advanced_request = db_service.advance_to_next_stage_composite(user_email, requested_group, config_id)
            if advanced_request:
                send_request_to_next_stage(advanced_request, config)
                logging.info(f"[{config_id}] Advanced request for {user_email} to next stage after approval.")
            else:
                logging.error(f"[{config_id}] Failed to advance request stage for {user_email} / {requested_group}.")
    else:
        logging.info(f"[{config_id}] Waiting on pending approvals from: {missing}")

def process_pending_reminders(config):
    """Sends reminders for requests that have been pending for too long."""
    try:
        requests = db_service.get_pending_requests_for_reminder(config)
        for req in requests:
            missing_approvers = db_service.get_missing_approvers_for_stage(req, config)
            if missing_approvers:
                subject = f"REMINDER: Approval Required for {req['user_to_onboard_email']}"
                body = (
                    f"Hello,\n\nThis is a reminder that your approval is still required for user "
                    f"'{req['user_to_onboard_email']}' to access '{req['requested_group']}'.\n\n"
                    f"Thank you,\n{config['team_alias']}"
                )
                send_email(missing_approvers, subject, body, config)
                db_service.update_request_status_composite(
                    req['user_to_onboard_email'], req['requested_group'], req['config_id'],
                    req['status'], f"Reminder sent to: {', '.join(missing_approvers)}"
                )
    except Exception as e:
        logging.error(f"[{config['config_id']}] Get pending reminders failed: {e}")

# --- Email Sending Helpers ---

def send_confirmation_email(user_email, config):
    subject = f"Welcome! Your Access to {config['team_alias']} is Granted"
    body = f"Hello,\n\nYour account ({user_email}) has been successfully onboarded.\n\nBest regards,\n{config['team_alias']}"
    send_email([user_email], subject, body, config)

def send_request_to_next_stage(request, config):
    """Sends an approval request email to the required approvers for the current stage."""
    stage_num = request['current_stage']
    user_email = request['user_to_onboard_email']
    group = request['requested_group']
    
    approvers = db_service.get_required_approvers_for_stage(request, config)
    stage_name = "Manager" if stage_num == 1 else f"Stage {stage_num} Owner"
    
    if not approvers:
        logging.error(f"Could not find approvers for {stage_name} for user {user_email}.")
        db_service.update_request_status_composite(
            user_email, group, config['config_id'], 'error', f"No approvers found for stage {stage_num}"
        )
        return

    subject = f"ACTION REQUIRED: Approve Onboarding for {user_email}"
    body = (
        f"Hello,\n\nThe user '{user_email}' has requested access to the '{group}' system, "
        f"which requires your approval.\n\nPlease reply to this email with 'Approved' or 'Rejected'.\n\n"
        f"Thank you,\n{config['team_alias']}"
    )
    send_email(approvers, subject, body, config)
    
    new_status = f"pending_{stage_name.lower().replace(' ','_')}_approval"
    db_service.update_request_status_composite(
        user_email, group, config['config_id'], new_status, 
        f"Approval request sent to {stage_name}(s): {', '.join(approvers)}"
    )